### ISSUE TITLE
[Authentication] Allow management of the access to a specific resource

### ISSUE THREAD

**Issue by thebillkidy** [thebillkidy/roadwork#1]
Only allow access to a specific resource (example: a user can only delete his/her own user object)
- Probably by checking the user_id in a table and matching it to the current user
- Will need user support in this lib then (atleast basic user support?)
- current thinking: add dynamic role ($owner, ...)
- A The validateFunction should check for the role == $owner, and should then check if the user_id == the current logged in user

**Comment by XavierGeerinck** [comment]
Base implementation done
