### ISSUE TITLE
change rolesAllowed to routeOptions so it is more dynamic

### ISSUE THREAD

**Issue by thebillkidy** [thebillkidy/roadwork#19]
Currently the parameter "rolesAllowed" is passed in the RouteGenerator. I think however it is better to rename this to "routeOptions" so that we can pass more options later on.

**Comment by taml** [comment]
Hello @thebillkidy I'd be interested in taking this up! Is it just a case of replacing any case of rolesAllowed in all files with routeOptions, so just a simple swap out?

**Comment by thebillkidy** [comment]
Hi @taml,

It's not a simple replace but it's a very easy task. If you look in the
Roadwork.js file you will see that the options are passed there as a key
from the main route object. (Example: options.routes.findAll.allowedRoles)
this should be changed so it's the main route object (such as
options.routes.findAll) and then the the RouteGenerator should of course
gets it references fixed too so they use routeOptions.allowedRoles where
needed.

If you need more help let me know! :) also make sure that the test coverage
stays on 100% after you finished the PR (you can run the tests locally or
just push them to the PR and see if Travis returns 100%)

**Comment by taml** [comment]
Thanks for the additional info, I've found two places in the Roadwork.js file to change options.routes.findAll.allowedRoles to options.routes.findAll, I've noticed in the code lower down there are similar pieces of code like 'options.routes.findOne.allowedRoles' do these need changing too so they exclude .allowedRoles? Could you provide an example of where I might use routeOptions.allowedRoles as I'm not too sure where to put that? Thanks!

**Comment by thebillkidy** [comment]
Yes all these code pieces need to be updated to include the correct reference then.

For an example where you can use the `routeOptions.allowedRoles`:

in the `RouteGenerator.js` you see a method called: `generateFindAll (model, rolesAllowed)`, the rolesAllowed should be renamed to: `routeOptions` and in that method every reference to rolesAllowed should then be updated to `routeOptions.allowedRoles`.

**Comment by taml** [comment]
Awesome thanks! Is it just that method in the RouteGenerator.js file that needs to be updated or do all methods in that file?

**Comment by thebillkidy** [comment]
Every method in that file has to be updated :)

**Comment by taml** [comment]
Ok! Right I think I'm almost there now, am I correct in thinking that the pattern passed into the returns should look like this? `return self.processRoles(model, routeOptions.allowedRoles, routeOptions);` so model, routeOptions.allowedRoles, routeOptions ?
Are there any other files that need updating besides Roadwork.js and RouteGenerator.js before I submit the PR?

**Comment by thebillkidy** [comment]
There is a fundamental problem in the return though, you can see: `return self.processRoles(model, routeOptions.allowedRoles, routeOptions);` that there are 2 variables `routeOptions` which are going to collide and this code won't work.

This mainly has to do due to the fact that I also have the `var routeOptions = {` everywhere, so by just renaming that variable to another one it should be fine. Maybe rename it to: `var routeConfig= {` and return it like: `return self.processRoles(model, routeOptions.allowedRoles, routeConfig);`

After that you should be fine to submit the PR

**Comment by taml** [comment]
I've made those changes, I've just spotted one other case where there are two routeOptions where I've changed it in `processRoles (model, routeOptions.allowedRoles, routeOptions) {` should I just swap this one to routeConfig too? As there's no routeOptions variable to change before this point in the code.

**Comment by thebillkidy** [comment]
The routeOptions parameter in that function is used as configuration, so you should indeed rename that routeOptions parameter to "routeConfig" 

So it becomes: `processRoles(model, rolesAllowed, routeConfig)` since you can not pass a reference in a method, and you passed the rolesAllowed in the other methods normally? (like you do: `return self.processRoles(model, routeOptions.allowedRoles, routeConfig);` so processRoles its header should be: `processRoles, rolesAllowed, routeConfig)`)

**Comment by taml** [comment]
Thank you. So the whole processRoles should look like this now? 

`   processRoles (model, allowedRoles, routeConfig) {
        if (allowedRoles && this.authentication) {
            routeConfig.config = {};
            routeConfig.config.auth = {
                strategy: this.authentication.strategyName,
                scope: routeConfig
            };
        }

        return routeConfig;
    }`

**Comment by thebillkidy** [comment]
Almost, the `scope: routeConfig` is not correct, scope should be an array stating which roles are allowed, so it should be `allowedRoles` instead

**Comment by thebillkidy** [comment]
Closing this issue now since it was resolved! Thanks for the help :)

**Comment by taml** [comment]
Thank you for all of your support @thebillkidy I really appreciate it!

**Comment by thebillkidy** [comment]
No problem :)
