### ISSUE TITLE
Add user support out of the box? (Could allow us for better roles, provide password on delete, ...)

### ISSUE THREAD

**Issue by thebillkidy** [thebillkidy/roadwork#7]

**Comment by thebillkidy** [comment]
moved to the auth lib https://github.com/thebillkidy/roadwork-authentication/projects/1

**Comment by XavierGeerinck** [comment]
Current thinking is to go deeper and work on a `Digital Twin` representation that can be used to call the RL algorithms on top of this. Hierarchy is thus important
